services:

  nginx:
    image: nginx:latest
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt

    depends_on:
      - app

  mariadb:
    image: mariadb:11
    restart: unless-stopped

    ports:
      - "3306:3306"

    env_file:
      - .env

    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}

    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    volumes:
      - mariadb-data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -uroot -p$$MARIADB_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10


  app:
    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - "8080"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      mariadb:
        condition: service_healthy

    restart: unless-stopped

volumes:
  mariadb-data: