spring:
  profiles:
    active: local
  application:
    name: senioron
  config:
    import: optional:classpath:application-secret.yml

jwt:
  secret: this-is-a-temporary-secret-key-for-senioron-jwt-please-change-later
  access-token-expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: senioron

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}

cloud:
  aws:
    region: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET}
