spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=trust
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 운영에서는 보통 validate 권장하지만 일단 유지

    properties:
      hibernate:
        format_sql: true
        show_sql: false

logging:
  level:
    root: INFO